# Generated by Django 5.1.4 on 2025-09-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='waveform_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
