# Generated by Django 5.2 on 2025-10-05 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_song_waveform_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, db_index=True, help_text='Single tag without spaces, e.g. house or #house', max_length=30, validators=[django.core.validators.RegexValidator('^\\S*$', 'Genre cannot contain spaces.')]),
        ),
    ]
