# Generated by Django 5.2 on 2025-10-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
